# SwiftLint configuration for Solar Atlas
opt_in_rules:
  - empty_count
  - first_where
  - closure_end_indentation
  - explicit_init
  - implicitly_unwrapped_optional

analyzer_rules:
  - unused_declaration
  - unused_import

force_cast:
  severity: error

force_try:
  severity: error

force_unwrap:
  severity: error

cyclomatic_complexity:
  warning: 15
  error: 20

file_length:
  warning: 400
  error: 500

type_body_length:
  warning: 200
  error: 250

function_body_length:
  warning: 60
  error: 100

identifier_name:
  min_length:
    warning: 3
    error: 2
  max_length:
    warning: 40
    error: 50
  excluded:
    - id
    - x
    - y
    - z

line_length:
  warning: 130
  ignores_function_declarations: true
  ignores_comments: true

trailing_whitespace:
  ignores_empty_lines: true

reporter: "xcode"
